apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: general-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "kube.cripto-country.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home1
            port:
              number: 80
  - host: "prueba.kube.cripto-country.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home2
            port:
              number: 80
