apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: criptoingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /prueba
        pathType: Mixed
            service: LoadBalance
            name: prueba
            port:
              number: 80