apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: market-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: 190.113.144.68/32
spec:
  rules:
  - host: "market.kube.cripto-country.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: market
            port:
              number: 80              